version: "3"
services:
  journaly-frontend:
    container_name: journaly-frontend
    image: journaly-frontend:latest
    stdin_open: true
    restart: always
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
